### ISSUE TITLE
Some keyboard doesn't work on start up

### ISSUE THREAD

**Issue by issu-shooter** [nhirokinet/bluelineconsole#17] opened 2020-12-20 11:09 UTC
Some keyboards like 8vim and TRIME, which are somehow old, don't work when launching BluLineConsole..You have to click the input box once before you input anything, or nothing will happen. 😣

Gboard also happens to have this problem, but less likely?

Anyway, NICE APP, keep on the good work! Best  Libre/Open source offline replacement for Google Assistant! You can make a legend!

**Comment by nhirokinet** [comment] 2020-12-20 12:00
Is this also the case in 1.0.7? A change is made on #10 (1.0.6) to address this problem, and one of testing environment had Gboard.

If so, can you tell me a little more detail like Android version for me to try to reproduce?

**Comment by issu-shooter** [comment] 2020-12-29 03:06
Well, I'm using 10 for now, using /e/OS which removes most google binaries. Not sure whether the OS variant will help.

**Comment by nhirokinet** [comment] 2020-12-29 08:33
I tried with emulator running Android 10 and 8vim, but did not reproduce it.

**Comment by issu-shooter** [comment] 2020-12-30 11:28
Just found another way to reproduce and I did it: Change keyboard when you started it. "Works" almost every time.
Another not so effective way is to search  for something doesn't present on the device then press backspace. Anyway if you see the input bar is missing, there could be a chance.

**Comment by nhirokinet** [comment] 2021-01-30 02:46
I'm not sure it is the same as your problem, but I could find some behavior about focusing, which seems to be changed at Android 9.

I improved behavior of focus after that. Also, in Android 9 or later it seems animation sometimes affects focus.

So can you try version 1.1.0 (or later)?

And if it is the case even in version 1.1.0, can you also try disabling animation from Blue Line Console config as workaround? From version 1.1.0 animation can be disabled in config.

**Comment by nhirokinet** [comment] 2021-01-30 02:52
(1.2.0 is going to be released, but 1.2.0 has no change which seems to affect this problem. If you use F-Droid, availability takes days from my release, but for this problem difference between 1.1.0 and 1.2.0 doesn't matter. Version 1.1.0 seems to be already available on 2021/1/29.)

**Comment by issu-shooter** [comment] 2021-02-03 23:41
I will test that, thanks for your hard work! I guess focusing is what I talked about. not a programmer actually.

**Comment by ivysrono** [comment] 2021-02-08 09:56
Enable setImeHintLocales English does't work with Trime 3.1.3.
Android11

**Comment by nhirokinet** [comment] 2021-02-08 11:26
`setImeHintLocales` is not so old interface (introduced in Android 7) and actual behavior depends on IMEs. I guess that is just not implemented in Trime and not Blue Line Console issue.

Effect of `setImeHintLocales` is [hintLocales](https://developer.android.com/reference/android/view/inputmethod/EditorInfo#hintLocales). I couldn't find the string "hintLocales" in Trime source code.

**Comment by ivysrono** [comment] 2021-02-08 12:20
So I open #84

**Comment by nhirokinet** [comment] 2021-07-08 13:24
No new report after about half an year after releasing 1.2.0. Closing this issue.

**Closed by nhirokinet** 2021-07-08 13:24 UTC
